export const ITEM_CATEGORIES = [
  "Clothing & Fashion",
  "Bags & Luggage",
  "Shoes & Footwear",
  "Jewelry & Accessories",
  "Beauty & Skin Care",
  "Makeup & Cosmetics",
  "Hair, Wigs & Extensions",
  "Perfume & Fragrance",
  "Spa & Body Care",
  "Health & Wellness",
  "Food & Groceries",
  "Drinks & Beverages",
  "Electronics & Gadgets",
  "Phones & Accessories",
  "Computers & Office",
  "Home & Kitchen",
  "Furniture & Decor",
  "Cleaning & Household",
  "Baby & Kids",
  "Books & Stationery",
  "Sports & Fitness",
  "Auto Parts & Accessories",
  "Tools & Hardware",
  "Gifts & Party Items",
  "Services",
  "Courses & Training",
  "Digital Products",
  "Other",
] as const;

export const ITEM_SUBCATEGORIES: Record<string, readonly string[]> = {
  "Clothing & Fashion": [
    "Women’s Clothing",
    "Men’s Clothing",
    "Traditional Wear",
    "Children’s Clothing",
    "Uniforms",
  ],
  "Bags & Luggage": [
    "Handbags",
    "Backpacks",
    "Travel Luggage",
    "Wallets & Purses",
  ],
  "Shoes & Footwear": [
    "Women’s Shoes",
    "Men’s Shoes",
    "Children’s Shoes",
    "Sports Shoes",
  ],
  "Jewelry & Accessories": [
    "Jewelry",
    "Watches",
    "Eyewear",
    "Fashion Accessories",
  ],
  "Beauty & Skin Care": [
    "Face Care",
    "Body Care",
    "Skin Treatments",
    "Beauty Tools",
  ],
  "Makeup & Cosmetics": [
    "Face Makeup",
    "Eye Makeup",
    "Lip Makeup",
    "Makeup Tools",
  ],
  "Hair, Wigs & Extensions": [
    "Wigs",
    "Hair Extensions",
    "Hair Products",
    "Hair Tools",
  ],
  "Perfume & Fragrance": [
    "Women’s Fragrance",
    "Men’s Fragrance",
    "Unisex Fragrance",
    "Home Fragrance",
  ],
  "Spa & Body Care": ["Massage", "Spa Treatments", "Bath & Body", "Nail Care"],
  "Health & Wellness": [
    "Supplements",
    "Personal Care",
    "Medical Supplies",
    "Wellness Services",
  ],
  "Food & Groceries": [
    "Fresh Food",
    "Packaged Food",
    "Snacks",
    "Baking & Cooking",
    "Pantry",
  ],
  "Drinks & Beverages": [
    "Water",
    "Soft Drinks",
    "Juices",
    "Tea & Coffee",
    "Alcoholic Drinks",
  ],
  "Electronics & Gadgets": [
    "Audio",
    "Cameras",
    "Gaming",
    "Smart Devices",
    "Electronic Accessories",
  ],
  "Phones & Accessories": [
    "Mobile Phones",
    "Phone Cases",
    "Chargers & Cables",
    "Phone Parts",
  ],
  "Computers & Office": [
    "Computers",
    "Computer Accessories",
    "Printers",
    "Office Equipment",
  ],
  "Home & Kitchen": [
    "Cookware",
    "Kitchen Appliances",
    "Home Appliances",
    "Bedding & Bath",
  ],
  "Furniture & Decor": [
    "Living Room",
    "Bedroom",
    "Office Furniture",
    "Home Decor",
  ],
  "Cleaning & Household": [
    "Cleaning Products",
    "Laundry",
    "Household Supplies",
    "Pest Control",
  ],
  "Baby & Kids": [
    "Baby Care",
    "Baby Clothing",
    "Toys & Games",
    "School Supplies",
  ],
  "Books & Stationery": [
    "Books",
    "Notebooks",
    "Writing Supplies",
    "Art Supplies",
  ],
  "Sports & Fitness": [
    "Fitness Equipment",
    "Sportswear",
    "Outdoor Recreation",
    "Team Sports",
  ],
  "Auto Parts & Accessories": [
    "Car Parts",
    "Motorcycle Parts",
    "Car Care",
    "Vehicle Accessories",
  ],
  "Tools & Hardware": [
    "Hand Tools",
    "Power Tools",
    "Building Materials",
    "Electrical & Plumbing",
  ],
  "Gifts & Party Items": [
    "Gift Items",
    "Party Supplies",
    "Flowers",
    "Personalized Gifts",
  ],
  Services: [
    "Beauty Services",
    "Professional Services",
    "Repairs & Maintenance",
    "Events",
    "Delivery & Logistics",
  ],
  "Courses & Training": [
    "Business",
    "Technology",
    "Beauty & Fashion",
    "Academic",
    "Creative Skills",
  ],
  "Digital Products": [
    "E-books",
    "Templates",
    "Software",
    "Digital Art",
    "Memberships",
  ],
  Other: [],
};

export function getCategorySubcategories(category: string): readonly string[] {
  return ITEM_SUBCATEGORIES[category.trim()] ?? [];
}
