export const SEDIFEX_PRICING_PLANS = [
  {
    name: 'Starter',
    badge: 'Start free',
    price: 'Free',
    billing: 'GHS 0 / month',
    bestFor: 'Testing Sedifex with a very small business.',
    highlight: false,
    includes: [
      '1 workspace',
      '1 staff/user',
      'Basic dashboard',
      'Basic items/products',
      'Basic customers',
      'Basic receipts/invoices',
      'Public Sedifex page',
      'QR code / public link',
      'Limited reports',
      'Sedifex branding',
      'Workspace switching when invited',
      'Branded text messaging available when message credits are purchased',
    ],
    limits: [
      'Up to 50 products/services',
      'Up to 30 receipts/invoices per month',
      'No custom domain',
      'No API keys',
      'No bulk email',
      'No advanced website builder templates',
      'No Sedifex Market product sync',
    ],
  },
  {
    name: 'Business',
    badge: 'Most popular',
    price: 'GHS 99',
    billing: 'per month · GHS 999 / year',
    bestFor: 'Sales, inventory, receipts, bookings, and marketplace visibility.',
    highlight: true,
    includes: [
      'Everything in Starter',
      'Inventory / items',
      'POS selling',
      'Receipts and invoices',
      'Customers and bookings',
      'Basic reports',
      'Basic website builder',
      'Quick Pay',
      'Sedifex Market listing',
      'Products/services sync to sedifexmarket.com',
      'Sedifex Market sales sync back into Sedifex',
      'Branded text messaging available when message credits are purchased',
      '2 staff/users',
      'Unlimited products/services under fair use',
    ],
    limits: [
      '1 business workspace per subscription',
      'Extra workspace add-on: GHS 49/month',
      'No custom domain',
      'No Products API or Bookings API',
      'Very large catalogs or high-volume imports may need review',
    ],
  },
  {
    name: 'Growth Website',
    badge: 'Best for online growth',
    price: 'GHS 199',
    billing: 'per month · GHS 1,999 / year',
    bestFor: 'A real business website connected to Sedifex and Sedifex Market.',
    highlight: false,
    includes: [
      'Everything in Business',
      'Full website builder',
      'Website template library',
      'Website preview with sample templates',
      'Custom domain setup',
      'SEO settings',
      'Social media links',
      'Gallery and promo content',
      'Website QR code and sharing tools',
      'Products API and Bookings API',
      'Website checkout setup',
      'Full sedifexmarket.com sales sync',
      'Website orders and marketplace orders sync into Sedifex',
      'Website sales report + marketplace sales report',
      'Branded text messaging available when message credits are purchased',
      '5 staff/users',
      'Unlimited products/services under fair use',
    ],
    limits: [
      '1 business workspace per subscription',
      'Extra workspace add-on: GHS 99/month',
      'Advanced custom integrations may require setup fee',
      'Very large catalogs or high API usage may need review',
    ],
  },
] as const

export const SEDIFEX_PRICING_RULES = [
  'Starter is limited to 50 products/services. Business and Growth Website include unlimited product/service uploads under fair use.',
  'Branded text messaging is available on all plans when message credits are purchased. Message credits are not bundled into monthly plan prices.',
  'One subscription includes one owned workspace. Paid plans can add extra owned workspaces at a discounted monthly rate.',
] as const
